name: Deploy to AWS Elastic Beanstalk (Dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Create and Upload App Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Zip Application Code
        run: zip -r ${{ github.event.repository.name }}.zip .

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pip install awscli
          AWS_VERSION_LABEL="${{ secrets.APP_NAME }}-1.0.0-${{ github.run_id }}"
          S3_KEY="${AWS_VERSION_LABEL}.zip"
          aws s3 cp ${{ github.event.repository.name }}.zip s3://${{ secrets.S3_BUCKET }}/${S3_KEY} --region ${{ secrets.AWS_REGION }}

      - name: Create New Application Version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          AWS_VERSION_LABEL="${{ secrets.APP_NAME }}-1.0.0-${{ github.run_id }}"
          S3_KEY="${AWS_VERSION_LABEL}.zip"
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.APP_NAME }} \
            --version-label $AWS_VERSION_LABEL \
            --region ${{ secrets.AWS_REGION }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=$S3_KEY \
            --description "GitHub Action Deployment" \
            --auto-create-application

  deploy:
    name: Deploy to Elastic Beanstalk (Dev)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install AWS EB CLI
        run: pip install awsebcli

      - name: Deploy Application Version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          AWS_VERSION_LABEL="${{ secrets.APP_NAME }}-1.0.0-${{ github.run_id }}"
          eb init ${{ secrets.APP_NAME }} --platform docker --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.ENV_NAME }}
          eb deploy --version $AWS_VERSION_LABEL
